# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a beta version to the Google Play"
  lane :beta do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'beta',
	package_name: 'com.goldenowl.e_commerce_shop_app',
	version_name: '1.0.9+8',
	json_key: 'D:\INTERN\ecommerce_app\android\play_config.json',aab_paths: ['D:\INTERN\ecommerce_app\android\app-release.aab'])
  end
  
  desc "Deploy a new version to the Google Play"
  lane :production do
	gradle(task: "clean bundleRelease")
    upload_to_play_store
  end
end
