# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a beta version to the Google Play"
  lane :beta do

    gb = google_play_track_version_codes(track: 'beta',json_key: 'play_config.json',package_name:'com.goldenowl.e_commerce_shop_app')
    
    version_updated  =  gb[0].to_i + 1

    upload_to_play_store(track: 'beta',
                          skip_upload_apk:true,
                          package_name: 'com.goldenowl.e_commerce_shop_app',
                          version_code:version_updated,
                          aab: '../build/app/outputs/bundle/release/app-release.aab',
                          json_key: 'play_config.json')
  end
  
  desc "Deploy a new version to the Google Play"
  lane :production do
	gradle(task: "clean bundleRelease")
    upload_to_play_store
  end
end

