name: Flutter CICD # action name
on:
  push:
    branches: [ git_action ]
tags:
- “v*”
jobs:
build:
runs-on: ubuntu-latest
env:
KEY_JKS: ${{ secrets.ANDROID_KEYSTORE_FILE }}
KEY_PATH: “upload-keystore1.jks”
KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
ALIAS_PASSWORD: ${{ secrets.KEYSTORE_KEY_ALIAS }}
steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
with:
distribution: 'adopt'
java-version: '12.x'
- name: Create key file
run: echo $ANDROID_KEYSTORE_FILE | base64 -di > upload-keystore1.jkss
- uses: subosito/flutter-action@v1
with:
flutter-version: '2.10.2' # change accordingly
- run: flutter pub get
- run: flutter build apk — release — split-per-abi
- run: flutter build appbundle
- name: Create github artifact release # disable this to save storage
uses: ncipollo/release-action@v1
with:
artifacts: “build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab”
token: ${{ secrets.GITHUB_TOKEN }} # this is automatically provided by github
commit:
- name: Upload app bundle artifact
uses: actions/upload-artifact@v2
with:
name: appbundle
path: build/app/outputs/bundle/release/app-release.aab

- name: Run Fastlane #Give a name to your action
uses: maierj/fastlane-action@v1.4.0 #Use this plugin developed by the community for the fastlane actions
with:
lane: upload_to_google_play_store #Here you can define the lane need to be executed with the work flow.
subdirectory: android #mention if the fastlane folder is inside the android folder.