name: Deploy

on:
  pull_request:
    types: [closed]

env:
  PROPERTIES_PATH: "android/key.properties"

jobs:
 distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      
      
      - name: Install bundle
        working-directory: android
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Configure Keystore
        working-directory: android
        run: |
          echo keyPassword=\${{ secrets.KEYSTORE_KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEYSTORE_STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEYSTORE_KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
       
      - run: echo "${{ secrets.KEYSTORE_TXT }}" | base64 --decode > android/app/update-keystore1.jks
        

      - name: Create Google Play Config file
        working-directory: android
        run : |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
          
      - name: Distribute app to Beta track 🚀
        working-directory: android
        run: bundle exec fastlane beta      