name: Deploy

on:
  push:
    branches: [ git_action ]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          
      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > android/app/upload-keystore1.jks
          echo "storeFile=keystore" >> android/keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> android/keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> android/keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> android/keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Create Google Play Config file
        run : |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}

      - name: Run Fastlane #Give a name to your action
        uses: maierj/fastlane-action@v1.4.0 #Use this plugin developed by the community for the fastlane actions
        with:
        lane: upload_to_google_play_store #Here you can define the lane need to be executed with the work flow.
        subdirectory: android #mention if the fastlane folder is inside the android folder.    
      - name: Distribute app to Beta track 🚀
        run: bundle exec fastlane beta          